// obj_player create
room_speed = 60
upKey = "W";
downKey = "S";
leftKey = "A";
rightKey = "D";
usingArrowKeys = false;
spd = 1;
jumpTime = 0;
jump = false;
moveTimeHeld = 0;
grav = 20;
attacking = false;
usingArrowKeys = false;
jumpPowerPerGravity=2
jumpPower = 0
timeOnCieling=0
maxDist = 400
chargeMaxSpd = 6
lastFacing = 0
timeHeld = 0
attacking =false
attacking2 = false
rocketFist=1